// Client generated by Zap v0.6.11 (https://github.com/red-blox/zap)
export declare const SendEvents: () => void
export declare const InitiateDialogue: {
	Fire: (Value: {
		id: string,
		nd: boolean,
	}) => void;
};
export declare const DialogueData: {
	SetCallback: (Callback: (Value: {
		success: boolean,
		dialogueId: string,
		data: {
			Interactions: Map<number, {
				Content: string,
				Title: string,
				Speed: number,
				Responses: ({
					Next: number,
					Content: string,
					Speed: number,
					TextColor?: Color3,
				})[],
			}>,
			ServerActions: Set<number>,
			ClientActions: Map<number, ({
				before?: ({
					type: number,
					data: {
						ActionData: "MoveCamera",
						target: CFrame,
						speed: number,
					},
				})[],
				after?: ({
					type: number,
					data: {
						ActionData: "MoveCamera",
						target: CFrame,
						speed: number,
					},
				})[],
			})[]>,
		},
	}) => void) => () => void;
};
